update workflow

diff --git a/.github/workflows/publishing2NuGet.yml b/.github/workflows/publishing2NuGet.yml
--- a/.github/workflows/publishing2NuGet.yml
+++ b/.github/workflows/publishing2NuGet.yml
@@ -54,7 +54,10 @@ jobs:
           IMAGE_TAG="$JAVA_OPENJDK_VEERSION-$VER"
           echo $IMAGE_TAG
 
-          [ -z "$IMAGE_NAME" ] || [ -z "$IMAGE_TAG" ] && echo "Failed on parsing $DOCKERFILE_PATH/Dockerfile , IMAGE NAME or TAG is NOT FOUND" && exit 1
+          if [ -z "$IMAGE_NAME" ] || [ -z "$IMAGE_TAG" ]; then
+            echo "Failed on parsing $DOCKERFILE_PATH/Dockerfile , IMAGE NAME or TAG is NOT FOUND"
+            exit 1
+          fi
 
       - name: Push Dockerfile
         run: |
