workflow_issue_comment with template

diff --git a/.github/workflows/publish_custom_docker_image_on_issue_comment.yml b/.github/workflows/publish_custom_docker_image_on_issue_comment.yml
--- a/.github/workflows/publish_custom_docker_image_on_issue_comment.yml
+++ b/.github/workflows/publish_custom_docker_image_on_issue_comment.yml
@@ -25,6 +25,7 @@ jobs:
       CLOUD_PROFILER_VERSION: NOT_SET
       DEFAULT_TAG: v1_java
       TAG: NOT_SET
+      IS_DECLINED: False
     runs-on: ubuntu-latest
     steps:
       - name: Parse issue comment body
@@ -38,13 +39,34 @@ jobs:
           [[ "$TAG" == "NOT_SET" ]] && echo "TAG=$(echo $DEFAULT_TAG)" >> $GITHUB_ENV
           for input in $(echo $ISSUE_COMMENT_BODY | tr -d '\r')
           do
-            [[ "$input" != "/build "* ]] && echo "Unknown cmd" && exit 1
+            [[ "$input" != "/build "* ]] && echo "IS_DECLINED=True" >> $GITHUB_ENV && continue
             [[ "$input" == *"BASE_IMAGE_NAME"* ]] && echo "BASE_IMAGE_NAME=$(echo $input | cut -d ':' -f2 | tr -d ' ')" >> $GITHUB_ENV && continue
             [[ "$input" == *"BASE_IMAGE_VERSION"* ]] && echo "BASE_IMAGE_VERSION=$(echo $input | cut -d ':' -f2 | tr -d ' ')" >> $GITHUB_ENV && continue
             [[ "$input" == *"OPEN_TELEMETRY_VERSION"* ]] && echo "OPEN_TELEMETRY_VERSION=$(echo $input | cut -d ':' -f2 | tr -d ' ')" >> $GITHUB_ENV && continue
             [[ "$input" == *"CLOUD_PROFILER_VERSION"* ]] && echo "CLOUD_PROFILER_VERSION=$(echo $input | cut -d ':' -f2 | tr -d ' ')" >> $GITHUB_ENV && continue
             [[ "$input" == *"TAG"* ]] && echo "TAG=$(echo $input | cut -d ':' -f2 | tr -d ' ')" >> $GITHUB_ENV && continue
           done
+      - name: Add issue comment reaction WIP or decline
+        if: contains(env.ISSUE_TITLE, 'java')
+        run: |
+          echo $IS_DECLINED
+          if [ $IS_DECLINED = False ]; then
+          gh api \
+            --method POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            /repos/$GITHUB_REPOSITORY/issues/comments/$ISSUE_COMMENT_ID/reactions \
+            -f content='-1' 
+            echo "/build cmd is missing" 
+            exit 1
+          else
+            gh api \
+              --method POST \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              /repos/$GITHUB_REPOSITORY/issues/comments/$ISSUE_COMMENT_ID/reactions \
+              -f content='eyes' 
+          fi
       - name: Check out repository
         if: contains(env.ISSUE_TITLE, 'java')
         uses: actions/checkout@v3
