workflow_issue_comment with template

diff --git a/.github/workflows/publish_custom_docker_image_on_issue_comment.yml b/.github/workflows/publish_custom_docker_image_on_issue_comment.yml
--- a/.github/workflows/publish_custom_docker_image_on_issue_comment.yml
+++ b/.github/workflows/publish_custom_docker_image_on_issue_comment.yml
@@ -58,10 +58,10 @@ jobs:
         run: |
           echo $IS_DECLINED
           if [ $IS_DECLINED = True ]; then
-          gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
-            /repos/$GITHUB_REPOSITORY/issues/comments/$ISSUE_COMMENT_ID/reactions -f content='-1' 
-            echo "/build cmd is missing" 
-            exit 1
+            gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
+              /repos/$GITHUB_REPOSITORY/issues/comments/$ISSUE_COMMENT_ID/reactions -f content='-1' 
+              echo "/build cmd is missing" 
+              exit 1
           else
             gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
               /repos/$GITHUB_REPOSITORY/issues/comments/$ISSUE_COMMENT_ID/reactions -f content='eyes' 
